//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una plantilla T4 de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  Abril 24 de 2012.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Domain.Core;
using Domain.MainModules.Entities;

namespace Applications.MainModule.PlanAccion.IServices
{
    public interface ISfTBL_ModuloPlanAccion_CategoriasManagementServices : IGenericServices<TBL_ModuloPlanAccion_Categorias>
    {
        /// <summary>
        /// Cuenta el total de registros
        /// </summary>
        /// <returns></returns>
        int CountbyPaged();

        /// <summary>
        /// Elimina la categoria seleccionada en la Base de Datos, verificando primero si tiene datos relacionados.
        /// </summary>
        /// <param name="idCategoria"></param>
        bool Delete(int idCategoria);
    }
}
    