//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por el motor de generacion de codigo de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  junio 18 de 2014.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 
using System;
using System.Collections.Generic;
using System.Linq;
using Applcations.MainModule.DocumentLibrary.IServices;
using Domain.MainModule.DocumentLibrary.Contracts;
using Domain.MainModules.Entities;
using Domain.Core.Specification;

namespace Applcations.MainModule.DocumentLibrary.Services
{
    public class SfTBL_ModuloDocumentosAnexos_CategoriasManagementServices : ISfTBL_ModuloDocumentosAnexos_CategoriasManagementServices
    {

         #region Fields
         readonly ITBL_ModuloDocumentosAnexos_CategoriasRepository _tblModuloDocumentosAnexosCategoriasRepository;
         #endregion

         #region Constructor
         /// <summary>
         /// Constructor de la Calse 
         /// </summary>
         public SfTBL_ModuloDocumentosAnexos_CategoriasManagementServices( ITBL_ModuloDocumentosAnexos_CategoriasRepository tblModuloDocumentosAnexosCategoriasRepository)
         {
            if (tblModuloDocumentosAnexosCategoriasRepository == null)
                throw new ArgumentNullException("tblModuloDocumentosAnexosCategoriasRepository");
            _tblModuloDocumentosAnexosCategoriasRepository = tblModuloDocumentosAnexosCategoriasRepository;
         }
         #endregion

         #region Members
         /// <summary>
         /// Crea una nueva instancia de la entidad 
         /// </summary>
         public TBL_ModuloDocumentosAnexos_Categorias NewEntity()
         {
            return new TBL_ModuloDocumentosAnexos_Categorias();
         }

         /// <summary>
         /// Inserta un nuevo registro en la Base de Datos.
         /// </summary>
         public void Add(TBL_ModuloDocumentosAnexos_Categorias entity)
         {
            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblModuloDocumentosAnexosCategoriasRepository.UnitOfWork;
            _tblModuloDocumentosAnexosCategoriasRepository.Add(entity);
            //Complete changes in this unit of work
            unitOfWork.Commit();
         }

          /// <summary>
          /// Actualiza el registro en la Base de Datos.
          /// </summary>
         public void Modify(TBL_ModuloDocumentosAnexos_Categorias entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Modificar : El objeto esta nulo."));

            var unitOfWork = _tblModuloDocumentosAnexosCategoriasRepository.UnitOfWork;
            _tblModuloDocumentosAnexosCategoriasRepository.Modify(entity);
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Elimina el registro en la Base de Datos.
          /// </summary>
         public void Remove(TBL_ModuloDocumentosAnexos_Categorias entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Eliminar : El objeto esta nulo."));

            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblModuloDocumentosAnexosCategoriasRepository.UnitOfWork;

            _tblModuloDocumentosAnexosCategoriasRepository.Remove(entity);

            //Complete changes in this unit of work
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Obtiene una única entidad filtrada por ID.
          /// </summary>
         public TBL_ModuloDocumentosAnexos_Categorias FindById(int id)
         {
            if (id == 0)
                throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

            Specification<TBL_ModuloDocumentosAnexos_Categorias> specification = new DirectSpecification<TBL_ModuloDocumentosAnexos_Categorias>(u => u.IdCategoria == id);

            return _tblModuloDocumentosAnexosCategoriasRepository.GetEntityBySpec(specification);
           
         }

		
		

          /// <summary>
          /// Obtiene el listado de entidades activas.
          /// </summary>
         public List<TBL_ModuloDocumentosAnexos_Categorias> FindBySpec(bool isActive)
         {
            Specification<TBL_ModuloDocumentosAnexos_Categorias> specification = new DirectSpecification<TBL_ModuloDocumentosAnexos_Categorias>(u => u.IsActive == isActive);
            return _tblModuloDocumentosAnexosCategoriasRepository.GetBySpec(specification).ToList();
         }

          /// <summary>
          /// Obtiene el listado de entidades activas y paginadas.
          /// </summary>
         public List<TBL_ModuloDocumentosAnexos_Categorias> FindPaged(int pageIndex, int pageCount)
         {
            if (pageIndex < 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageIndex, "pageIndex");

            if (pageCount <= 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageCount, "pageCount");


            Specification<TBL_ModuloDocumentosAnexos_Categorias> onlyEnabledSpec = new DirectSpecification<TBL_ModuloDocumentosAnexos_Categorias>(u => u.IsActive);

            return _tblModuloDocumentosAnexosCategoriasRepository.GetPagedElements(pageIndex, pageCount, u => u.IdCategoria, onlyEnabledSpec, true).ToList();
         }

         #endregion

         #region IDisposable Members

        /// <summary>
        /// Release all resources
        /// </summary>
        public void Dispose()
        {
            //release used unit of work
            //if you have many repositories but  lifetime is per resolve only need
            //dispose one

            if (_tblModuloDocumentosAnexosCategoriasRepository != null)
            {
                _tblModuloDocumentosAnexosCategoriasRepository.UnitOfWork.Dispose();
            }
        }

        #endregion
    }
}
    