//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por el motor de generacion de codigo de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  junio 18 de 2014.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 
using System;
using System.Collections.Generic;
using System.Linq;
using Applcations.MainModule.DocumentLibrary.IServices;
using Applcations.MainModule.DocumentLibrary.Resources;
using Domain.MainModule.DocumentLibrary.Contracts;
using Domain.MainModule.DocumentLibrary.Spec;
using Domain.MainModule.Reclamos.Contracts;
using Domain.MainModules.Entities;
using Domain.Core.Specification;
using System.Transactions;

namespace Applcations.MainModule.DocumentLibrary.Services
{
    public class SfTBL_ModuloDocumentosAnexos_CarpetasManagementServices : ISfTBL_ModuloDocumentosAnexos_CarpetasManagementServices
    {

         #region Fields
         readonly ITBL_ModuloDocumentosAnexos_CarpetasRepository _tblModuloDocumentosAnexosCarpetasRepository;
        private readonly ITBL_ModuloReclamos_ReclamoRepository _reclamoRepository;
         #endregion

         #region Constructor
         /// <summary>
         /// Constructor de la Calse 
         /// </summary>
         public SfTBL_ModuloDocumentosAnexos_CarpetasManagementServices( ITBL_ModuloDocumentosAnexos_CarpetasRepository tblModuloDocumentosAnexosCarpetasRepository, ITBL_ModuloReclamos_ReclamoRepository reclamoRepository)
         {
            if (tblModuloDocumentosAnexosCarpetasRepository == null)
                throw new ArgumentNullException("tblModuloDocumentosAnexosCarpetasRepository");
            _tblModuloDocumentosAnexosCarpetasRepository = tblModuloDocumentosAnexosCarpetasRepository;
             _reclamoRepository = reclamoRepository;
         }
         #endregion

         #region Members
         /// <summary>
         /// Crea una nueva instancia de la entidad 
         /// </summary>
         public TBL_ModuloDocumentosAnexos_Carpetas NewEntity()
         {
            return new TBL_ModuloDocumentosAnexos_Carpetas();
         }

         /// <summary>
         /// Inserta un nuevo registro en la Base de Datos.
         /// </summary>
         public void Add(TBL_ModuloDocumentosAnexos_Carpetas entity)
         {
            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblModuloDocumentosAnexosCarpetasRepository.UnitOfWork;
            _tblModuloDocumentosAnexosCarpetasRepository.Add(entity);
            //Complete changes in this unit of work
            unitOfWork.Commit();
         }

          /// <summary>
          /// Actualiza el registro en la Base de Datos.
          /// </summary>
         public void Modify(TBL_ModuloDocumentosAnexos_Carpetas entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Modificar : El objeto esta nulo."));

            var unitOfWork = _tblModuloDocumentosAnexosCarpetasRepository.UnitOfWork;
            _tblModuloDocumentosAnexosCarpetasRepository.Modify(entity);
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Elimina el registro en la Base de Datos.
          /// </summary>
         public void Remove(TBL_ModuloDocumentosAnexos_Carpetas entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Eliminar : El objeto esta nulo."));

            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblModuloDocumentosAnexosCarpetasRepository.UnitOfWork;

            _tblModuloDocumentosAnexosCarpetasRepository.Remove(entity);

            //Complete changes in this unit of work
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Obtiene una única entidad filtrada por ID.
          /// </summary>
         public TBL_ModuloDocumentosAnexos_Carpetas FindById(int id)
         {
            if (id == 0)
                throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

            Specification<TBL_ModuloDocumentosAnexos_Carpetas> specification = new DirectSpecification<TBL_ModuloDocumentosAnexos_Carpetas>(u => u.IdFolder == id);

            return _tblModuloDocumentosAnexosCarpetasRepository.GetEntityBySpec(specification);
           
         }


		

          /// <summary>
          /// Obtiene el listado de entidades activas.
          /// </summary>
         public List<TBL_ModuloDocumentosAnexos_Carpetas> FindBySpec(bool isActive)
         {
            Specification<TBL_ModuloDocumentosAnexos_Carpetas> specification = new DirectSpecification<TBL_ModuloDocumentosAnexos_Carpetas>(u => u.IsActive == isActive);
            return _tblModuloDocumentosAnexosCarpetasRepository.GetBySpec(specification).ToList();
         }

          /// <summary>
          /// Obtiene el listado de entidades activas y paginadas.
          /// </summary>
         public List<TBL_ModuloDocumentosAnexos_Carpetas> FindPaged(int pageIndex, int pageCount)
         {
            if (pageIndex < 0)
                throw new ArgumentException(Messages.exception_InvalidPageIndex, "pageIndex");

            if (pageCount <= 0)
                throw new ArgumentException(Messages.exception_InvalidPageCount, "pageCount");


            Specification<TBL_ModuloDocumentosAnexos_Carpetas> onlyEnabledSpec = new DirectSpecification<TBL_ModuloDocumentosAnexos_Carpetas>(u => u.IsActive);

            return _tblModuloDocumentosAnexosCarpetasRepository.GetPagedElements(pageIndex, pageCount, u => u.IdFolder, onlyEnabledSpec, true).ToList();
         }


         public List<TBL_ModuloDocumentosAnexos_Carpetas> GetFoldersByIdReclamo(string idReclamo)
         {

             var onlyEnabledSpec = new CarpetasPorContratoCodeSpecifications(idReclamo);

             return _tblModuloDocumentosAnexosCarpetasRepository.GetBySpec(onlyEnabledSpec).ToList();
         }

         public bool SaveFolder(string idParent, string idcategory, string nombre, string idReclamo, string idUser)
         {
             var txSettings = new TransactionOptions()
             {
                 Timeout = TransactionManager.DefaultTimeout,
                 IsolationLevel = IsolationLevel.Serializable
             };

             using (var scope = new TransactionScope(TransactionScopeOption.Required, txSettings))
             {
                 var unitOfWork = _tblModuloDocumentosAnexosCarpetasRepository.UnitOfWork;

                 var oFolder = NewEntity();
                 oFolder.CreatedBy = idUser;
                 oFolder.CreatedOn = DateTime.Now;
                 oFolder.IdCategoria = Convert.ToInt32(idcategory);
                 if (!string.IsNullOrEmpty(idParent))
                     oFolder.IdParent = Convert.ToInt32(idParent);
                 oFolder.IsActive = true;
                 oFolder.Nombre = nombre;
                 oFolder.ModifiedBy = idUser;
                 oFolder.ModifiedOn = DateTime.Now;

                 var oContrato = LoadReclamo(idReclamo);
                 if (oContrato == null)
                 {
                     throw new Exception(string.Format("Error al obtener el reclamo {0} desde la Base de Datos.", idReclamo));
                 }

                 oFolder.TBL_ModuloReclamos_Reclamo.Add(oContrato);

                 _tblModuloDocumentosAnexosCarpetasRepository.Add(oFolder);

                 unitOfWork.Commit();

                 scope.Complete();

                 return true;
             }


         }


         private TBL_ModuloReclamos_Reclamo LoadReclamo(string idReclamo)
         {
             return _reclamoRepository.GetReclamoById(Convert.ToInt32(idReclamo));
         }

         #endregion

         #region IDisposable Members

        /// <summary>
        /// Release all resources
        /// </summary>
        public void Dispose()
        {
            //release used unit of work
            //if you have many repositories but  lifetime is per resolve only need
            //dispose one

            if (_tblModuloDocumentosAnexosCarpetasRepository != null)
            {
                _tblModuloDocumentosAnexosCarpetasRepository.UnitOfWork.Dispose();
            }
        }

        #endregion
    }
}
    