//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por el motor de generacion de codigo de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  junio 18 de 2014.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 
using System;
using System.Collections.Generic;
using System.Linq;
using Application.MainModule.AccionesPC.IServices;
using Domain.MainModule.AccionesPC.Contracts;
using Domain.MainModules.Entities;
using Domain.Core.Specification;

namespace Application.MainModule.AccionesPC.Services
{
    public class SfTBL_ModuloAPC_TrackingManagementServices : ISfTBL_ModuloAPC_TrackingManagementServices
    {

         #region Fields
         readonly ITBL_ModuloAPC_TrackingRepository _tblModuloApcTrackingRepository;
         #endregion

         #region Constructor
         /// <summary>
         /// Constructor de la Calse 
         /// </summary>
         public SfTBL_ModuloAPC_TrackingManagementServices( ITBL_ModuloAPC_TrackingRepository tblModuloApcTrackingRepository)
         {
            if (tblModuloApcTrackingRepository == null)
                throw new ArgumentNullException("tblModuloApcTrackingRepository");
            _tblModuloApcTrackingRepository = tblModuloApcTrackingRepository;
         }
         #endregion

         #region Members
         /// <summary>
         /// Crea una nueva instancia de la entidad 
         /// </summary>
         public TBL_ModuloAPC_Tracking NewEntity()
         {
            return new TBL_ModuloAPC_Tracking();
         }

         /// <summary>
         /// Inserta un nuevo registro en la Base de Datos.
         /// </summary>
         public void Add(TBL_ModuloAPC_Tracking entity)
         {
            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblModuloApcTrackingRepository.UnitOfWork;
            _tblModuloApcTrackingRepository.Add(entity);
            //Complete changes in this unit of work
            unitOfWork.Commit();
         }

          /// <summary>
          /// Actualiza el registro en la Base de Datos.
          /// </summary>
         public void Modify(TBL_ModuloAPC_Tracking entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Modificar : El objeto esta nulo."));

            var unitOfWork = _tblModuloApcTrackingRepository.UnitOfWork;
            _tblModuloApcTrackingRepository.Modify(entity);
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Elimina el registro en la Base de Datos.
          /// </summary>
         public void Remove(TBL_ModuloAPC_Tracking entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Eliminar : El objeto esta nulo."));

            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblModuloApcTrackingRepository.UnitOfWork;

            _tblModuloApcTrackingRepository.Remove(entity);

            //Complete changes in this unit of work
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Obtiene una única entidad filtrada por ID.
          /// </summary>
         public TBL_ModuloAPC_Tracking FindById(int id)
         {
            if (id == 0)
                throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

            Specification<TBL_ModuloAPC_Tracking> specification = new DirectSpecification<TBL_ModuloAPC_Tracking>(u => u.IdTracking == id);

            return _tblModuloApcTrackingRepository.GetEntityBySpec(specification);
           
         }

		

          /// <summary>
          /// Obtiene el listado de entidades activas.
          /// </summary>
         public List<TBL_ModuloAPC_Tracking> FindBySpec(bool isActive)
         {
            Specification<TBL_ModuloAPC_Tracking> specification = new DirectSpecification<TBL_ModuloAPC_Tracking>(u => u.IsActive == isActive);
            return _tblModuloApcTrackingRepository.GetBySpec(specification).ToList();
         }

          /// <summary>
          /// Obtiene el listado de entidades activas y paginadas.
          /// </summary>
         public List<TBL_ModuloAPC_Tracking> FindPaged(int pageIndex, int pageCount)
         {
            if (pageIndex < 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageIndex, "pageIndex");

            if (pageCount <= 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageCount, "pageCount");


            Specification<TBL_ModuloAPC_Tracking> onlyEnabledSpec = new DirectSpecification<TBL_ModuloAPC_Tracking>(u => u.IsActive);

            return _tblModuloApcTrackingRepository.GetPagedElements(pageIndex, pageCount, u => u.IdTracking, onlyEnabledSpec, true).ToList();
         }

         #endregion

         #region IDisposable Members

        /// <summary>
        /// Release all resources
        /// </summary>
        public void Dispose()
        {
            //release used unit of work
            //if you have many repositories but  lifetime is per resolve only need
            //dispose one

            if (_tblModuloApcTrackingRepository != null)
            {
                _tblModuloApcTrackingRepository.UnitOfWork.Dispose();
            }
        }

        #endregion
    }
}
    