//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Domain.MainModule.DocumentLibrary.Contracts;
using Infraestructure.Data.Core;
using Infraestructure.Data.Core.Extensions;
using Infraestructure.Data.DocumentLibrary.Resources;
using Infrastructure.CrossCutting.Logging;
using Domain.MainModules.Entities;
using Domain.Core.Specification;
using Infrastructure.Data.MainModule.UnitOfWork;

namespace Infraestructure.Data.DocumentLibrary.Repositories
{
    public class TBL_ModuloDocumentosAnexos_ContenidoRepository : GenericRepository<TBL_ModuloDocumentosAnexos_Contenido>, ITBL_ModuloDocumentosAnexos_ContenidoRepository 
    {
        public TBL_ModuloDocumentosAnexos_ContenidoRepository(IMainModuleUnitOfWork unitOfWork, ITraceManager traceManager) : base(unitOfWork, traceManager)
        {
        }

        public List<TBL_ModuloDocumentosAnexos_Contenido> FindDocumentsByFolder(ISpecification<TBL_ModuloDocumentosAnexos_Contenido> specification)
        {
            //validate specification
            if (specification == null)
                throw new ArgumentNullException("specification");


            //var set = _currentUnitOfWork.CreateSet<TBL_ModuloWorkFlow_Rutas>();
            //return set.Include()

            var activeContext = UnitOfWork as IMainModuleUnitOfWork;
            if (activeContext != null)
            {

                //perform operation in this repository
                var specific = specification.SatisfiedBy();
                return activeContext.TBL_ModuloDocumentosAnexos_Contenido
                                    //.Include(r => r.TBL_ModuloDocumentosAnexos_Documento.TBL_ModuloDocumentosAnexos_Carpetas)
                                    .Where(specific)
                                    .ToList();
            }
            throw new InvalidOperationException(string.Format(
                CultureInfo.InvariantCulture,
                Messages.exception_InvalidStoreContext,
                GetType().Name));
        }
    }
}
    