//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using System.Collections.Generic;
using Domain.Core;
using Domain.Core.Specification;
using Domain.MainModules.Entities;

namespace Domain.MainModule.WorkFlow.Contracts
{
    public interface ITBL_ModuloWorkFlow_CamposValidacionRepository : IRepository<TBL_ModuloWorkFlow_CamposValidacion>
    {
        List<TBL_ModuloWorkFlow_CamposValidacion> FindCamposBySpec(
            ISpecification<TBL_ModuloWorkFlow_CamposValidacion> specification);
    }
}
    