//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using Domain.Core;
using Domain.MainModules.Entities;
using Domain.Core.Specification;

namespace Domain.MainModule.Contracts
{
    public interface ITBL_Maestra_Customers_DocumentacionRepository : IRepository<TBL_Maestra_Customers_Documentacion>
    {
       TBL_Maestra_Customers_Documentacion FindDocumentBySpec(
            ISpecification<TBL_Maestra_Customers_Documentacion> specification);

        List<TBL_Maestra_Customers_Documentacion> FindDocumentsBySpec(int pageIndex, int pageCount,
                                                                      Expression
                                                                          <
                                                                          Func<TBL_Maestra_Customers_Documentacion, int>
                                                                          > orderByExpression,
                                                                      ISpecification
                                                                          <TBL_Maestra_Customers_Documentacion>
                                                                          specification, bool ascending);
    }
}
    