//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por el motor de generacion de codigo de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  junio 18 de 2014.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 
using System;
using System.Collections.Generic;
using System.Linq;
using Domain.MainModules.Entities;
using Domain.Core.Specification;
using Domain.MainModule.Reclamos.Contracts;
using Application.MainModule.Reclamos.IServices;
using Domain.MainModule.Reclamos.Spec;

namespace Application.MainModule.Reclamos.Services
{
    public class SfTBL_ModuloReclamos_CategoriasReclamoManagementServices : ISfTBL_ModuloReclamos_CategoriasReclamoManagementServices
    {

         #region Fields
         readonly ITBL_ModuloReclamos_CategoriasReclamoRepository _TBLModuloReclamosCategoriasReclamoRepository;
         #endregion

         #region Constructor
         /// <summary>
         /// Constructor de la Calse 
         /// </summary>
         public SfTBL_ModuloReclamos_CategoriasReclamoManagementServices( ITBL_ModuloReclamos_CategoriasReclamoRepository TBLModuloReclamosCategoriasReclamoRepository)
         {
            if (TBLModuloReclamosCategoriasReclamoRepository == null)
                throw new ArgumentNullException("TBLModuloReclamosCategoriasReclamoRepository");
            _TBLModuloReclamosCategoriasReclamoRepository = TBLModuloReclamosCategoriasReclamoRepository;
         }
         #endregion

         #region Members
         /// <summary>
         /// Crea una nueva instancia de la entidad 
         /// </summary>
         public TBL_ModuloReclamos_CategoriasReclamo NewEntity()
         {
            return new TBL_ModuloReclamos_CategoriasReclamo();
         }

         /// <summary>
         /// Inserta un nuevo registro en la Base de Datos.
         /// </summary>
         public void Add(TBL_ModuloReclamos_CategoriasReclamo entity)
         {
            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _TBLModuloReclamosCategoriasReclamoRepository.UnitOfWork;
            _TBLModuloReclamosCategoriasReclamoRepository.Add(entity);
            //Complete changes in this unit of work
            unitOfWork.Commit();
         }

          /// <summary>
          /// Actualiza el registro en la Base de Datos.
          /// </summary>
         public void Modify(TBL_ModuloReclamos_CategoriasReclamo entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Modificar : El objeto esta nulo."));

            var unitOfWork = _TBLModuloReclamosCategoriasReclamoRepository.UnitOfWork;
            _TBLModuloReclamosCategoriasReclamoRepository.Modify(entity);
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Elimina el registro en la Base de Datos.
          /// </summary>
         public void Remove(TBL_ModuloReclamos_CategoriasReclamo entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Eliminar : El objeto esta nulo."));

            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _TBLModuloReclamosCategoriasReclamoRepository.UnitOfWork;

            _TBLModuloReclamosCategoriasReclamoRepository.Remove(entity);

            //Complete changes in this unit of work
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Obtiene una única entidad filtrada por ID.
          /// </summary>
         public TBL_ModuloReclamos_CategoriasReclamo FindById(int id)
         {
            if (id == 0)
                throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

            Specification<TBL_ModuloReclamos_CategoriasReclamo> specification = new DirectSpecification<TBL_ModuloReclamos_CategoriasReclamo>(u => u.IdCategoriaReclamo == id);

            return _TBLModuloReclamosCategoriasReclamoRepository.GetCategoriaBySpec(specification);
           
         }

		 /*
         public TBL_ModuloReclamos_CategoriasReclamo FindById(string id)
         {
             if (string.IsNullOrEmpty(id))
                 throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

              Specification<TBL_ModuloReclamos_CategoriasReclamo> specification = new DirectSpecification<TBL_ModuloReclamos_CategoriasReclamo>(u => u.Code == id);

            return _TBLModuloReclamosCategoriasReclamoRepository.GetEntityBySpec(specification);
         }
		 */

		

          /// <summary>
          /// Obtiene el listado de entidades activas.
          /// </summary>
         public List<TBL_ModuloReclamos_CategoriasReclamo> FindBySpec(bool isActive)
         {
            Specification<TBL_ModuloReclamos_CategoriasReclamo> specification = new DirectSpecification<TBL_ModuloReclamos_CategoriasReclamo>(u => u.IsActive == isActive);
            return _TBLModuloReclamosCategoriasReclamoRepository.GetBySpec(specification).ToList();
         }

          /// <summary>
          /// Obtiene el listado de entidades activas y paginadas.
          /// </summary>
         public List<TBL_ModuloReclamos_CategoriasReclamo> FindPaged(int pageIndex, int pageCount)
         {
            if (pageIndex < 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageIndex, "pageIndex");

            if (pageCount <= 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageCount, "pageCount");


            Specification<TBL_ModuloReclamos_CategoriasReclamo> onlyEnabledSpec = new DirectSpecification<TBL_ModuloReclamos_CategoriasReclamo>(u => u.IdCategoriaReclamo != null);

            return _TBLModuloReclamosCategoriasReclamoRepository.GetPagedElements(pageIndex, pageCount, u => u.CreateOn, onlyEnabledSpec, true).ToList();
         }

        public List<TBL_ModuloReclamos_CategoriasReclamo> FindPaged(int pageIndex, int pageCount,string search)
             {
                 if (pageIndex < 0)
                     throw new ArgumentException(Resources.Messages.exception_InvalidPageIndex, "pageIndex");

                 if (pageCount <= 0)
                     throw new ArgumentException(Resources.Messages.exception_InvalidPageCount, "pageCount");


                 if (!string.IsNullOrEmpty(search))
                 {
                     Specification<TBL_ModuloReclamos_CategoriasReclamo> onlyEnabledSpec = new DirectSpecification<TBL_ModuloReclamos_CategoriasReclamo>
                        (u => (u.Nombre.Contains(search) ||
                        u.TBL_ModuloReclamos_TipoReclamo.Nombre.Contains(search) ||
                        u.SubCategoria.Contains(search) ||
                        u.Area.Contains(search) ||
                        u.TBL_Admin_Usuarios.Nombres.Contains(search)));


                     return _TBLModuloReclamosCategoriasReclamoRepository.GetPagedElements(pageIndex, pageCount, u => u.CreateOn, onlyEnabledSpec, true).ToList();
                 }
                 else
                 {
                     Specification<TBL_ModuloReclamos_CategoriasReclamo> onlyEnabledSpec = new DirectSpecification<TBL_ModuloReclamos_CategoriasReclamo>(u => u.IdCategoriaReclamo != null);

                     return _TBLModuloReclamosCategoriasReclamoRepository.GetPagedElements(pageIndex, pageCount, u => u.CreateOn, onlyEnabledSpec, true).ToList();
                 }
             }

        public int CountByPaged(string search)
         {
             if (!string.IsNullOrEmpty(search))
             {

                 Specification<TBL_ModuloReclamos_CategoriasReclamo> onlyEnabledSpec = new DirectSpecification<TBL_ModuloReclamos_CategoriasReclamo>
                        (u => (u.Nombre.Contains(search) ||
                        u.TBL_ModuloReclamos_TipoReclamo.Nombre.Contains(search) ||
                        u.SubCategoria.Contains(search) ||
                        u.Area.Contains(search) ||
                        u.TBL_Admin_Usuarios.Nombres.Contains(search)));
                 return _TBLModuloReclamosCategoriasReclamoRepository.GetBySpec(onlyEnabledSpec).Count();
             }
             else
             {
                 Specification<TBL_ModuloReclamos_CategoriasReclamo> onlyEnabledSpec = new DirectSpecification<TBL_ModuloReclamos_CategoriasReclamo>(u => u.IdCategoriaReclamo != null);

                 return _TBLModuloReclamosCategoriasReclamoRepository.GetBySpec(onlyEnabledSpec).Count();
             }
         }

         #endregion

         #region IDisposable Members

        /// <summary>
        /// Release all resources
        /// </summary>
        public void Dispose()
        {
            //release used unit of work
            //if you have many repositories but  lifetime is per resolve only need
            //dispose one

            if (_TBLModuloReclamosCategoriasReclamoRepository != null)
            {
                _TBLModuloReclamosCategoriasReclamoRepository.UnitOfWork.Dispose();
            }
        }

        #endregion

        #region IService Members

        public List<TBL_ModuloReclamos_CategoriasReclamo> GetByTipoReclamo(int idTipoReclamo)
        {
            return _TBLModuloReclamosCategoriasReclamoRepository.GetBySpec(TBL_ModuloReclamos_CategoriasReclamo_Spec.SpecByTipoReclamo(idTipoReclamo))
                                                                .ToList();
        }

        #endregion
    }
}
    