//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenters.Documentos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presenters.Documentos.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos son requeridos!!.
        /// </summary>
        internal static string CamposObligatorios {
            get {
                return ResourceManager.GetString("CamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al  eliminar el objeto {0}. Comuníquese con el Administrador del sistema..
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al descargar el archivo..
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al editar el objeto.  Comuníquese con el Administrador del sistema..
        /// </summary>
        internal static string EditError {
            get {
                return ResourceManager.GetString("EditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro [{0}] ya se encuentra registrado en la Base de Datos..
        /// </summary>
        internal static string EntityExist {
            get {
                return ResourceManager.GetString("EntityExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de lectuta de Identificador del {0}..
        /// </summary>
        internal static string ErrorLecturaID {
            get {
                return ResourceManager.GetString("ErrorLecturaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Fecha Límite MultiOrden es Diferente de nulo y el parámetro de validación es nulo. Por favor, comuníquese con el administrador del sistema..
        /// </summary>
        internal static string ErrorMultiorden {
            get {
                return ResourceManager.GetString("ErrorMultiorden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al leer la cadena de consulta!!.
        /// </summary>
        internal static string ErrorQueryString {
            get {
                return ResourceManager.GetString("ErrorQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha límite MultiOrden no puede ser mayor a la fecha: {0}.
        /// </summary>
        internal static string ErrorValidacionFechaMultiOrden {
            get {
                return ResourceManager.GetString("ErrorValidacionFechaMultiOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al recuperar el objeto [{0}] desde la Base de Datos. Comuníquese con el Administrador del sistema..
        /// </summary>
        internal static string GetObjectError {
            get {
                return ResourceManager.GetString("GetObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El {0} ha sido  {1} por el usuario  {2}  en la fecha  {3}..
        /// </summary>
        internal static string LogDeCambios {
            get {
                return ResourceManager.GetString("LogDeCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha seleccionado un archivo.
        /// </summary>
        internal static string NotSelectFile {
            get {
                return ResourceManager.GetString("NotSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso {0} terminó con errores. Comuníquese con el administrador del sistema.
        /// </summary>
        internal static string ProcessError {
            get {
                return ResourceManager.GetString("ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso completado satisfactoriamente!!!.
        /// </summary>
        internal static string ProcessOk {
            get {
                return ResourceManager.GetString("ProcessOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la  manipulación de la Cadena de Consulta. Acceso no autorizado: 401.
        /// </summary>
        internal static string QueryStringError {
            get {
                return ResourceManager.GetString("QueryStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar el registro en la base de datos. Contáctese con el administrador del sistema..
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar por lo menos un registro de la lista {0}.
        /// </summary>
        internal static string SelectedRecors {
            get {
                return ResourceManager.GetString("SelectedRecors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superó el tamaño máximo permitido a cargar de un archivo ({0} Mega(s)).
        /// </summary>
        internal static string SizeMaxFileError {
            get {
                return ResourceManager.GetString("SizeMaxFileError", resourceCulture);
            }
        }
    }
}
