//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using Domain.Core.Entities;

namespace Domain.MainModules.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(TBL_Admin_Departamentos))]
    [KnownType(typeof(TBL_Admin_PaisMoneda))]
    [KnownType(typeof(TBL_Admin_Plantillas))]
    
    public partial class TBL_Admin_Paises: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int IdPais
        {
            get { return _idPais; }
            set
            {
                if (_idPais != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IdPais' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _idPais = value;
                    OnPropertyChanged("IdPais");
                }
            }
        }
        private int _idPais;
    
        [DataMember]
        public string Codigo
        {
            get { return _codigo; }
            set
            {
                if (_codigo != value)
                {
                    _codigo = value;
                    OnPropertyChanged("Codigo");
                }
            }
        }
        private string _codigo;
    
        [DataMember]
        public string Nombre
        {
            get { return _nombre; }
            set
            {
                if (_nombre != value)
                {
                    _nombre = value;
                    OnPropertyChanged("Nombre");
                }
            }
        }
        private string _nombre;
    
        [DataMember]
        public string Globalizacion
        {
            get { return _globalizacion; }
            set
            {
                if (_globalizacion != value)
                {
                    _globalizacion = value;
                    OnPropertyChanged("Globalizacion");
                }
            }
        }
        private string _globalizacion;
    
        [DataMember]
        public bool IsActive
        {
            get { return _isActive; }
            set
            {
                if (_isActive != value)
                {
                    _isActive = value;
                    OnPropertyChanged("IsActive");
                }
            }
        }
        private bool _isActive;
    
        [DataMember]
        public string CreateBy
        {
            get { return _createBy; }
            set
            {
                if (_createBy != value)
                {
                    _createBy = value;
                    OnPropertyChanged("CreateBy");
                }
            }
        }
        private string _createBy;
    
        [DataMember]
        public Nullable<System.DateTime> CreateOn
        {
            get { return _createOn; }
            set
            {
                if (_createOn != value)
                {
                    _createOn = value;
                    OnPropertyChanged("CreateOn");
                }
            }
        }
        private Nullable<System.DateTime> _createOn;
    
        [DataMember]
        public string ModifiedBy
        {
            get { return _modifiedBy; }
            set
            {
                if (_modifiedBy != value)
                {
                    _modifiedBy = value;
                    OnPropertyChanged("ModifiedBy");
                }
            }
        }
        private string _modifiedBy;
    
        [DataMember]
        public Nullable<System.DateTime> ModifiedOn
        {
            get { return _modifiedOn; }
            set
            {
                if (_modifiedOn != value)
                {
                    _modifiedOn = value;
                    OnPropertyChanged("ModifiedOn");
                }
            }
        }
        private Nullable<System.DateTime> _modifiedOn;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<TBL_Admin_Departamentos> TBL_Admin_Departamentos
        {
            get
            {
                if (_tBL_Admin_Departamentos == null)
                {
                    _tBL_Admin_Departamentos = new TrackableCollection<TBL_Admin_Departamentos>();
                    _tBL_Admin_Departamentos.CollectionChanged += FixupTBL_Admin_Departamentos;
                }
                return _tBL_Admin_Departamentos;
            }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_Departamentos, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tBL_Admin_Departamentos != null)
                    {
                        _tBL_Admin_Departamentos.CollectionChanged -= FixupTBL_Admin_Departamentos;
                    }
                    _tBL_Admin_Departamentos = value;
                    if (_tBL_Admin_Departamentos != null)
                    {
                        _tBL_Admin_Departamentos.CollectionChanged += FixupTBL_Admin_Departamentos;
                    }
                    OnNavigationPropertyChanged("TBL_Admin_Departamentos");
                }
            }
        }
        private TrackableCollection<TBL_Admin_Departamentos> _tBL_Admin_Departamentos;
    
        [DataMember]
        public TrackableCollection<TBL_Admin_PaisMoneda> TBL_Admin_PaisMoneda
        {
            get
            {
                if (_tBL_Admin_PaisMoneda == null)
                {
                    _tBL_Admin_PaisMoneda = new TrackableCollection<TBL_Admin_PaisMoneda>();
                    _tBL_Admin_PaisMoneda.CollectionChanged += FixupTBL_Admin_PaisMoneda;
                }
                return _tBL_Admin_PaisMoneda;
            }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_PaisMoneda, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tBL_Admin_PaisMoneda != null)
                    {
                        _tBL_Admin_PaisMoneda.CollectionChanged -= FixupTBL_Admin_PaisMoneda;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (TBL_Admin_PaisMoneda item in _tBL_Admin_PaisMoneda)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _tBL_Admin_PaisMoneda = value;
                    if (_tBL_Admin_PaisMoneda != null)
                    {
                        _tBL_Admin_PaisMoneda.CollectionChanged += FixupTBL_Admin_PaisMoneda;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (TBL_Admin_PaisMoneda item in _tBL_Admin_PaisMoneda)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("TBL_Admin_PaisMoneda");
                }
            }
        }
        private TrackableCollection<TBL_Admin_PaisMoneda> _tBL_Admin_PaisMoneda;
    
        [DataMember]
        public TrackableCollection<TBL_Admin_Plantillas> TBL_Admin_Plantillas
        {
            get
            {
                if (_tBL_Admin_Plantillas == null)
                {
                    _tBL_Admin_Plantillas = new TrackableCollection<TBL_Admin_Plantillas>();
                    _tBL_Admin_Plantillas.CollectionChanged += FixupTBL_Admin_Plantillas;
                }
                return _tBL_Admin_Plantillas;
            }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_Plantillas, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tBL_Admin_Plantillas != null)
                    {
                        _tBL_Admin_Plantillas.CollectionChanged -= FixupTBL_Admin_Plantillas;
                    }
                    _tBL_Admin_Plantillas = value;
                    if (_tBL_Admin_Plantillas != null)
                    {
                        _tBL_Admin_Plantillas.CollectionChanged += FixupTBL_Admin_Plantillas;
                    }
                    OnNavigationPropertyChanged("TBL_Admin_Plantillas");
                }
            }
        }
        private TrackableCollection<TBL_Admin_Plantillas> _tBL_Admin_Plantillas;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            TBL_Admin_Departamentos.Clear();
            TBL_Admin_PaisMoneda.Clear();
            TBL_Admin_Plantillas.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupTBL_Admin_Departamentos(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TBL_Admin_Departamentos item in e.NewItems)
                {
                    item.TBL_Admin_Paises = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TBL_Admin_Departamentos", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TBL_Admin_Departamentos item in e.OldItems)
                {
                    if (ReferenceEquals(item.TBL_Admin_Paises, this))
                    {
                        item.TBL_Admin_Paises = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TBL_Admin_Departamentos", item);
                    }
                }
            }
        }
    
        private void FixupTBL_Admin_PaisMoneda(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TBL_Admin_PaisMoneda item in e.NewItems)
                {
                    item.TBL_Admin_Paises = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TBL_Admin_PaisMoneda", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TBL_Admin_PaisMoneda item in e.OldItems)
                {
                    if (ReferenceEquals(item.TBL_Admin_Paises, this))
                    {
                        item.TBL_Admin_Paises = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TBL_Admin_PaisMoneda", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }
    
        private void FixupTBL_Admin_Plantillas(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TBL_Admin_Plantillas item in e.NewItems)
                {
                    item.TBL_Admin_Paises = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TBL_Admin_Plantillas", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TBL_Admin_Plantillas item in e.OldItems)
                {
                    if (ReferenceEquals(item.TBL_Admin_Paises, this))
                    {
                        item.TBL_Admin_Paises = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TBL_Admin_Plantillas", item);
                    }
                }
            }
        }

        #endregion
    }
}
