//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una plantilla T4 de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  Abril 24 de 2012.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Domain.Core;
using Domain.MainModules.Entities;
using System.Collections.Generic;
using System;

namespace Application.MainModule.Documentos.IServices
{
    public interface ISfTBL_ModuloDocumentos_DocumentoManagementServices 
        : IGenericServices<TBL_ModuloDocumentos_Documento>
    {
        TBL_ModuloDocumentos_Documento GetDocumentoByIdWithAttachments(int id);

        List<TBL_ModuloDocumentos_Documento> FindTotalDocsByFilters(string filtroNombre, Int32 filtroIdEstado,
                                                                    Int32 filtroIdResponsable);

        List<TBL_ModuloDocumentos_Documento> FindDocsPublicadosByFilters(string filtroNombre);

        List<TBL_ModuloDocumentos_Documento> FindMyDocsByFilters(string filtroNombre, Int32 filtroIdEstado,
                                                                 Int32 filtroIdUsuario);

        TBL_ModuloDocumentos_Documento GetDocumentoByIdWithCategories(int id);

        TBL_ModuloDocumentos_Documento GetDocumentoByIdWithUsers(int id);
    }
}
    