//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por el motor de generacion de codigo de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  junio 18 de 2014.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 
using System;
using System.Collections.Generic;
using System.Linq;
using Application.MainModule.Documentos.IServices;
using Domain.MainModule.Documentos.Contracts;
using Domain.MainModules.Entities;
using Domain.Core.Specification;

namespace Application.MainModule.Documentos.Services
{
    public class SfTBL_ModuloDocumentos_LogCambiosManagementServices : ISfTBL_ModuloDocumentos_LogCambiosManagementServices
    {

         #region Fields
         readonly ITBL_ModuloDocumentos_LogCambiosRepository _tblModuloDocumentosLogCambiosRepository;
         #endregion

         #region Constructor
         /// <summary>
         /// Constructor de la Calse 
         /// </summary>
         public SfTBL_ModuloDocumentos_LogCambiosManagementServices( ITBL_ModuloDocumentos_LogCambiosRepository tblModuloDocumentosLogCambiosRepository)
         {
            if (tblModuloDocumentosLogCambiosRepository == null)
                throw new ArgumentNullException("tblModuloDocumentosLogCambiosRepository");
            _tblModuloDocumentosLogCambiosRepository = tblModuloDocumentosLogCambiosRepository;
         }
         #endregion

         #region Members
         /// <summary>
         /// Crea una nueva instancia de la entidad 
         /// </summary>
         public TBL_ModuloDocumentos_LogCambios NewEntity()
         {
            return new TBL_ModuloDocumentos_LogCambios();
         }

         /// <summary>
         /// Inserta un nuevo registro en la Base de Datos.
         /// </summary>
         public void Add(TBL_ModuloDocumentos_LogCambios entity)
         {
            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblModuloDocumentosLogCambiosRepository.UnitOfWork;
            _tblModuloDocumentosLogCambiosRepository.Add(entity);
            //Complete changes in this unit of work
            unitOfWork.Commit();
         }

          /// <summary>
          /// Actualiza el registro en la Base de Datos.
          /// </summary>
         public void Modify(TBL_ModuloDocumentos_LogCambios entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Modificar : El objeto esta nulo."));

            var unitOfWork = _tblModuloDocumentosLogCambiosRepository.UnitOfWork;
            _tblModuloDocumentosLogCambiosRepository.Modify(entity);
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Elimina el registro en la Base de Datos.
          /// </summary>
         public void Remove(TBL_ModuloDocumentos_LogCambios entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Eliminar : El objeto esta nulo."));

            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblModuloDocumentosLogCambiosRepository.UnitOfWork;

            _tblModuloDocumentosLogCambiosRepository.Remove(entity);

            //Complete changes in this unit of work
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Obtiene una única entidad filtrada por ID.
          /// </summary>
         public TBL_ModuloDocumentos_LogCambios FindById(int id)
         {
            if (id == 0)
                throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

            Specification<TBL_ModuloDocumentos_LogCambios> specification = new DirectSpecification<TBL_ModuloDocumentos_LogCambios>(u => u.IdLog == id);

            return _tblModuloDocumentosLogCambiosRepository.GetEntityBySpec(specification);
           
         }

		 /*
         public TBL_ModuloDocumentos_LogCambios FindById(string id)
         {
             if (string.IsNullOrEmpty(id))
                 throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

              Specification<TBL_ModuloDocumentos_LogCambios> specification = new DirectSpecification<TBL_ModuloDocumentos_LogCambios>(u => u.Code == id);

            return _TBLModuloDocumentosLogCambiosRepository.GetEntityBySpec(specification);
         }
		 */

		

          /// <summary>
          /// Obtiene el listado de entidades activas.
          /// </summary>
         public List<TBL_ModuloDocumentos_LogCambios> FindBySpec(bool isActive)
         {
            Specification<TBL_ModuloDocumentos_LogCambios> specification = new DirectSpecification<TBL_ModuloDocumentos_LogCambios>(u => u.IsActive == isActive);
            return _tblModuloDocumentosLogCambiosRepository.GetBySpec(specification).ToList();
         }

          /// <summary>
          /// Obtiene el listado de entidades activas y paginadas.
          /// </summary>
         public List<TBL_ModuloDocumentos_LogCambios> FindPaged(int pageIndex, int pageCount)
         {
            if (pageIndex < 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageIndex, "pageIndex");

            if (pageCount <= 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageCount, "pageCount");


            Specification<TBL_ModuloDocumentos_LogCambios> onlyEnabledSpec = new DirectSpecification<TBL_ModuloDocumentos_LogCambios>(u => u.IsActive);

            return _tblModuloDocumentosLogCambiosRepository.GetPagedElements(pageIndex, pageCount, u => u.IdLog, onlyEnabledSpec, true).ToList();
         }

         #endregion

         #region IDisposable Members

        /// <summary>
        /// Release all resources
        /// </summary>
        public void Dispose()
        {
            //release used unit of work
            //if you have many repositories but  lifetime is per resolve only need
            //dispose one

            if (_tblModuloDocumentosLogCambiosRepository != null)
            {
                _tblModuloDocumentosLogCambiosRepository.UnitOfWork.Dispose();
            }
        }

        #endregion
    }
}
    