//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por el motor de generacion de codigo de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  junio 18 de 2014.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 
using System;
using System.Collections.Generic;
using System.Linq;
using Applications.MainModule.Admin.IServices;
using Domain.MainModules.Entities;
using Domain.Core.Specification;
using Domain.MainModule.Contracts;

namespace Applications.MainModule.Admin.Services
{
    public class SfTBL_Admin_DescripcionesTipoProductoManagementServices : ISfTBL_Admin_DescripcionesTipoProductoManagementServices
    {

         #region Fields
         readonly ITBL_Admin_DescripcionesTipoProductoRepository _tblAdminDescripcionesTipoProductoRepository;
         #endregion

         #region Constructor
         /// <summary>
         /// Constructor de la Calse 
         /// </summary>
         public SfTBL_Admin_DescripcionesTipoProductoManagementServices( ITBL_Admin_DescripcionesTipoProductoRepository tblAdminDescripcionesTipoProductoRepository)
         {
            if (tblAdminDescripcionesTipoProductoRepository == null)
                throw new ArgumentNullException("tblAdminDescripcionesTipoProductoRepository");
            _tblAdminDescripcionesTipoProductoRepository = tblAdminDescripcionesTipoProductoRepository;
         }
         #endregion

         #region Members
         /// <summary>
         /// Crea una nueva instancia de la entidad 
         /// </summary>
         public TBL_Admin_DescripcionesTipoProducto NewEntity()
         {
            return new TBL_Admin_DescripcionesTipoProducto();
         }

         /// <summary>
         /// Inserta un nuevo registro en la Base de Datos.
         /// </summary>
         public void Add(TBL_Admin_DescripcionesTipoProducto entity)
         {
            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblAdminDescripcionesTipoProductoRepository.UnitOfWork;
            _tblAdminDescripcionesTipoProductoRepository.Add(entity);
            //Complete changes in this unit of work
            unitOfWork.Commit();
         }

          /// <summary>
          /// Actualiza el registro en la Base de Datos.
          /// </summary>
         public void Modify(TBL_Admin_DescripcionesTipoProducto entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Modificar : El objeto esta nulo."));

            var unitOfWork = _tblAdminDescripcionesTipoProductoRepository.UnitOfWork;
            _tblAdminDescripcionesTipoProductoRepository.Modify(entity);
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Elimina el registro en la Base de Datos.
          /// </summary>
         public void Remove(TBL_Admin_DescripcionesTipoProducto entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Eliminar : El objeto esta nulo."));

            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblAdminDescripcionesTipoProductoRepository.UnitOfWork;

            _tblAdminDescripcionesTipoProductoRepository.Remove(entity);

            //Complete changes in this unit of work
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Obtiene una única entidad filtrada por ID.
          /// </summary>
         public TBL_Admin_DescripcionesTipoProducto FindById(int id)
         {
            if (id == 0)
                throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

            Specification<TBL_Admin_DescripcionesTipoProducto> specification = new DirectSpecification<TBL_Admin_DescripcionesTipoProducto>(u => u.IdDescripcion== id);

            return _tblAdminDescripcionesTipoProductoRepository.GetEntityBySpec(specification);
           
         }

		 /*
         public TBL_Admin_DescripcionesTipoProducto FindById(string id)
         {
             if (string.IsNullOrEmpty(id))
                 throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

              Specification<TBL_Admin_DescripcionesTipoProducto> specification = new DirectSpecification<TBL_Admin_DescripcionesTipoProducto>(u => u.Code == id);

            return _TBLAdminDescripcionesTipoProductoRepository.GetEntityBySpec(specification);
         }
		 */

		

          /// <summary>
          /// Obtiene el listado de entidades activas.
          /// </summary>
         public List<TBL_Admin_DescripcionesTipoProducto> FindBySpec(bool isActive)
         {
            Specification<TBL_Admin_DescripcionesTipoProducto> specification = new DirectSpecification<TBL_Admin_DescripcionesTipoProducto>(u => u.IsActive == isActive);
            return _tblAdminDescripcionesTipoProductoRepository.GetBySpec(specification).ToList();
         }

          /// <summary>
          /// Obtiene el listado de entidades activas y paginadas.
          /// </summary>
         public List<TBL_Admin_DescripcionesTipoProducto> FindPaged(int pageIndex, int pageCount)
         {
            if (pageIndex < 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageIndex, "pageIndex");

            if (pageCount <= 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageCount, "pageCount");


            Specification<TBL_Admin_DescripcionesTipoProducto> onlyEnabledSpec = new DirectSpecification<TBL_Admin_DescripcionesTipoProducto>(u => u.IsActive);

            return _tblAdminDescripcionesTipoProductoRepository.GetPagedElements(pageIndex, pageCount, u => u.IdDescripcion, onlyEnabledSpec, true).ToList();
         }

         /// <summary>
         /// Obtiene una única entidad filtrada por ID.
         /// </summary>
         public TBL_Admin_DescripcionesTipoProducto ObtenerDescripcionPorCodigo(string codigo)
         {
             if (string.IsNullOrEmpty(codigo))
                 throw new ArgumentNullException(string.Format("Busqueda por codigo : El parametro es nulo."));

             Specification<TBL_Admin_DescripcionesTipoProducto> specification = new DirectSpecification<TBL_Admin_DescripcionesTipoProducto>(u => u.Codigo.Equals(codigo));

             return _tblAdminDescripcionesTipoProductoRepository.GetEntityBySpec(specification);

         }

         #endregion

         #region IDisposable Members

        /// <summary>
        /// Release all resources
        /// </summary>
        public void Dispose()
        {
            //release used unit of work
            //if you have many repositories but  lifetime is per resolve only need
            //dispose one

            if (_tblAdminDescripcionesTipoProductoRepository != null)
            {
                _tblAdminDescripcionesTipoProductoRepository.UnitOfWork.Dispose();
            }
        }

        #endregion
    }
}
    