//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por el motor de generacion de codigo de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  junio 18 de 2014.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 
using System;
using System.Collections.Generic;
using System.Linq;
using Domain.MainModules.Entities;
using Domain.Core.Specification;
using Domain.MainModule.Reclamos.Contracts;
using Application.MainModule.Reclamos.IServices;

namespace Application.MainModule.Reclamos.Services
{
    public class SfTBL_ModuloReclamos_TipoReclamoManagementServices : ISfTBL_ModuloReclamos_TipoReclamoManagementServices
    {

         #region Fields
         readonly ITBL_ModuloReclamos_TipoReclamoRepository _TBLModuloReclamosTipoReclamoRepository;
         #endregion

         #region Constructor
         /// <summary>
         /// Constructor de la Calse 
         /// </summary>
         public SfTBL_ModuloReclamos_TipoReclamoManagementServices( ITBL_ModuloReclamos_TipoReclamoRepository TBLModuloReclamosTipoReclamoRepository)
         {
            if (TBLModuloReclamosTipoReclamoRepository == null)
                throw new ArgumentNullException("TBLModuloReclamosTipoReclamoRepository");
            _TBLModuloReclamosTipoReclamoRepository = TBLModuloReclamosTipoReclamoRepository;
         }
         #endregion

         #region Members
         /// <summary>
         /// Crea una nueva instancia de la entidad 
         /// </summary>
         public TBL_ModuloReclamos_TipoReclamo NewEntity()
         {
            return new TBL_ModuloReclamos_TipoReclamo();
         }

         /// <summary>
         /// Inserta un nuevo registro en la Base de Datos.
         /// </summary>
         public void Add(TBL_ModuloReclamos_TipoReclamo entity)
         {
            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _TBLModuloReclamosTipoReclamoRepository.UnitOfWork;
            _TBLModuloReclamosTipoReclamoRepository.Add(entity);
            //Complete changes in this unit of work
            unitOfWork.Commit();
         }

          /// <summary>
          /// Actualiza el registro en la Base de Datos.
          /// </summary>
         public void Modify(TBL_ModuloReclamos_TipoReclamo entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Modificar : El objeto esta nulo."));

            var unitOfWork = _TBLModuloReclamosTipoReclamoRepository.UnitOfWork;
            _TBLModuloReclamosTipoReclamoRepository.Modify(entity);
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Elimina el registro en la Base de Datos.
          /// </summary>
         public void Remove(TBL_ModuloReclamos_TipoReclamo entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Eliminar : El objeto esta nulo."));

            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _TBLModuloReclamosTipoReclamoRepository.UnitOfWork;

            _TBLModuloReclamosTipoReclamoRepository.Remove(entity);

            //Complete changes in this unit of work
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Obtiene una única entidad filtrada por ID.
          /// </summary>
         public TBL_ModuloReclamos_TipoReclamo FindById(int id)
         {
            if (id == 0)
                throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

            Specification<TBL_ModuloReclamos_TipoReclamo> specification = new DirectSpecification<TBL_ModuloReclamos_TipoReclamo>(u => u.IdTipoReclamo == id);

            return _TBLModuloReclamosTipoReclamoRepository.GetEntityBySpec(specification);
           
         }

		 /*
         public TBL_ModuloReclamos_TipoReclamo FindById(string id)
         {
             if (string.IsNullOrEmpty(id))
                 throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

              Specification<TBL_ModuloReclamos_TipoReclamo> specification = new DirectSpecification<TBL_ModuloReclamos_TipoReclamo>(u => u.Code == id);

            return _TBLModuloReclamosTipoReclamoRepository.GetEntityBySpec(specification);
         }
		 */

		

          /// <summary>
          /// Obtiene el listado de entidades activas.
          /// </summary>
         public List<TBL_ModuloReclamos_TipoReclamo> FindBySpec(bool isActive)
         {
            Specification<TBL_ModuloReclamos_TipoReclamo> specification = new DirectSpecification<TBL_ModuloReclamos_TipoReclamo>(u => u.IsActive == isActive);
            return _TBLModuloReclamosTipoReclamoRepository.GetBySpec(specification).ToList();
         }

          /// <summary>
          /// Obtiene el listado de entidades activas y paginadas.
          /// </summary>
         public List<TBL_ModuloReclamos_TipoReclamo> FindPaged(int pageIndex, int pageCount)
         {
            if (pageIndex < 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageIndex, "pageIndex");

            if (pageCount <= 0)
                throw new ArgumentException(Resources.Messages.exception_InvalidPageCount, "pageCount");


            Specification<TBL_ModuloReclamos_TipoReclamo> onlyEnabledSpec = new DirectSpecification<TBL_ModuloReclamos_TipoReclamo>(u => u.IsActive);

            return _TBLModuloReclamosTipoReclamoRepository.GetPagedElements(pageIndex, pageCount, u => u.CreateOn, onlyEnabledSpec, true).ToList();
         }

         #endregion

         #region IDisposable Members

        /// <summary>
        /// Release all resources
        /// </summary>
        public void Dispose()
        {
            //release used unit of work
            //if you have many repositories but  lifetime is per resolve only need
            //dispose one

            if (_TBLModuloReclamosTipoReclamoRepository != null)
            {
                _TBLModuloReclamosTipoReclamoRepository.UnitOfWork.Dispose();
            }
        }

        #endregion
    }
}
    