//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using Domain.Core.Entities;

namespace Domain.MainModules.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(TBL_ModuloAPC_Solicitud))]
    
    public partial class TBL_ModuloAPC_Tracking: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public decimal IdTracking
        {
            get { return _idTracking; }
            set
            {
                if (_idTracking != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IdTracking' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _idTracking = value;
                    OnPropertyChanged("IdTracking");
                }
            }
        }
        private decimal _idTracking;
    
        [DataMember]
        public decimal IdSolicitud
        {
            get { return _idSolicitud; }
            set
            {
                if (_idSolicitud != value)
                {
                    ChangeTracker.RecordOriginalValue("IdSolicitud", _idSolicitud);
                    if (!IsDeserializing)
                    {
                        if (TBL_ModuloAPC_Solicitud != null && TBL_ModuloAPC_Solicitud.IdSolucitudAPC != value)
                        {
                            TBL_ModuloAPC_Solicitud = null;
                        }
                    }
                    _idSolicitud = value;
                    OnPropertyChanged("IdSolicitud");
                }
            }
        }
        private decimal _idSolicitud;
    
        [DataMember]
        public string Autor
        {
            get { return _autor; }
            set
            {
                if (_autor != value)
                {
                    _autor = value;
                    OnPropertyChanged("Autor");
                }
            }
        }
        private string _autor;
    
        [DataMember]
        public string EstadoAnterior
        {
            get { return _estadoAnterior; }
            set
            {
                if (_estadoAnterior != value)
                {
                    _estadoAnterior = value;
                    OnPropertyChanged("EstadoAnterior");
                }
            }
        }
        private string _estadoAnterior;
    
        [DataMember]
        public string Accion
        {
            get { return _accion; }
            set
            {
                if (_accion != value)
                {
                    _accion = value;
                    OnPropertyChanged("Accion");
                }
            }
        }
        private string _accion;
    
        [DataMember]
        public string Nuevoestado
        {
            get { return _nuevoestado; }
            set
            {
                if (_nuevoestado != value)
                {
                    _nuevoestado = value;
                    OnPropertyChanged("Nuevoestado");
                }
            }
        }
        private string _nuevoestado;
    
        [DataMember]
        public string NuevoResponsable
        {
            get { return _nuevoResponsable; }
            set
            {
                if (_nuevoResponsable != value)
                {
                    _nuevoResponsable = value;
                    OnPropertyChanged("NuevoResponsable");
                }
            }
        }
        private string _nuevoResponsable;
    
        [DataMember]
        public bool IsActive
        {
            get { return _isActive; }
            set
            {
                if (_isActive != value)
                {
                    _isActive = value;
                    OnPropertyChanged("IsActive");
                }
            }
        }
        private bool _isActive;
    
        [DataMember]
        public string CreateBy
        {
            get { return _createBy; }
            set
            {
                if (_createBy != value)
                {
                    _createBy = value;
                    OnPropertyChanged("CreateBy");
                }
            }
        }
        private string _createBy;
    
        [DataMember]
        public Nullable<System.DateTime> CreateOn
        {
            get { return _createOn; }
            set
            {
                if (_createOn != value)
                {
                    _createOn = value;
                    OnPropertyChanged("CreateOn");
                }
            }
        }
        private Nullable<System.DateTime> _createOn;
    
        [DataMember]
        public string ModifiedBy
        {
            get { return _modifiedBy; }
            set
            {
                if (_modifiedBy != value)
                {
                    _modifiedBy = value;
                    OnPropertyChanged("ModifiedBy");
                }
            }
        }
        private string _modifiedBy;
    
        [DataMember]
        public Nullable<System.DateTime> ModifiedOn
        {
            get { return _modifiedOn; }
            set
            {
                if (_modifiedOn != value)
                {
                    _modifiedOn = value;
                    OnPropertyChanged("ModifiedOn");
                }
            }
        }
        private Nullable<System.DateTime> _modifiedOn;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TBL_ModuloAPC_Solicitud TBL_ModuloAPC_Solicitud
        {
            get { return _tBL_ModuloAPC_Solicitud; }
            set
            {
                if (!ReferenceEquals(_tBL_ModuloAPC_Solicitud, value))
                {
                    var previousValue = _tBL_ModuloAPC_Solicitud;
                    _tBL_ModuloAPC_Solicitud = value;
                    FixupTBL_ModuloAPC_Solicitud(previousValue);
                    OnNavigationPropertyChanged("TBL_ModuloAPC_Solicitud");
                }
            }
        }
        private TBL_ModuloAPC_Solicitud _tBL_ModuloAPC_Solicitud;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            TBL_ModuloAPC_Solicitud = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupTBL_ModuloAPC_Solicitud(TBL_ModuloAPC_Solicitud previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TBL_ModuloAPC_Tracking.Contains(this))
            {
                previousValue.TBL_ModuloAPC_Tracking.Remove(this);
            }
    
            if (TBL_ModuloAPC_Solicitud != null)
            {
                if (!TBL_ModuloAPC_Solicitud.TBL_ModuloAPC_Tracking.Contains(this))
                {
                    TBL_ModuloAPC_Solicitud.TBL_ModuloAPC_Tracking.Add(this);
                }
    
                IdSolicitud = TBL_ModuloAPC_Solicitud.IdSolucitudAPC;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TBL_ModuloAPC_Solicitud")
                    && (ChangeTracker.OriginalValues["TBL_ModuloAPC_Solicitud"] == TBL_ModuloAPC_Solicitud))
                {
                    ChangeTracker.OriginalValues.Remove("TBL_ModuloAPC_Solicitud");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TBL_ModuloAPC_Solicitud", previousValue);
                }
                if (TBL_ModuloAPC_Solicitud != null && !TBL_ModuloAPC_Solicitud.ChangeTracker.ChangeTrackingEnabled)
                {
                    TBL_ModuloAPC_Solicitud.StartTracking();
                }
            }
        }

        #endregion
    }
}
